name: Java Application Deployment to EC2 (Ubuntu)

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Java Application
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK 1.8 for Maven
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Deploy WAR file to EC2 (Ubuntu)
      - name: Deploy WAR to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}/simple-webapp.war

      # Execute remote commands on Ubuntu EC2
      - name: Install and Configure Apache Tomcat on Ubuntu EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y tomcat9
            sudo systemctl start tomcat9
            sudo systemctl enable tomcat9
            sudo mv ${{ secrets.TARGET_DIR }}/simple-webapp.war /var/lib/tomcat9/webapps/
            sudo systemctl restart tomcat9
